url: https://sudoexplorer.github.io/jekyll-dash/
title: sudoexplorer
author: sudoexplorer
email: explorereverywhere@gmail.com
description: > # this means to ignore newlines until "show_exerpts:#Write an awesome description for your new site here. You can edit this #line in _config.yml. It will appear in your document head meta (for#Google search results) and in your feed.xml site description."
   The meta intellectual explorer. Thoughts and opinions about Technology, Science, Gaming, Internet, Life, Food, Music, Lifestyle and Universe.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: 

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/sudoexplorer
      icon: twitter-square
      color: cyan
    - #url: https://bitbrain.itch.io
      #icon: itch-io
     # color: red
    - #url: https://github.com/bitbrain
     # icon: github-square
     # color: purple

  show_author: true

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
